[tool.poetry]
name = "video-downloader-bot"
version = "0.1.0"
description = "Telegram bot for downloading videos from social networks"
authors = ["Jag_k <jag-k@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = "^20.1"
aiohttp = "^3.8.3"
pytube = "^12.1.2"
python-dotenv = "^0.21.1"
pytz = "^2022.7.1"

[tool.poetry.group.dev.dependencies]
babel = "^2.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
