[tool.poetry]
name = "video-downloader-bot"
version = "0.1.0"
description = "Telegram bot for downloading videos from social networks"
authors = ["Jag_k <jag-k@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "cli" }]

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = "20.0a4"
aiohttp = "^3.8.3"
pytube = "^12.1.0"
setuptools = "^65.5.0"
python-dotenv = "^0.21.0"

[tool.poetry.dev-dependencies]
Babel = "^2.11.0"

[tool.poetry.scripts]
update-locale = "cli.__main__:update_locale"
full-update-locale = "cli.__main__:full_update_locale"
compile-locale = "cli:compile_locale"
extract-locale = "cli:extract_locale"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
